<a href="https://colab.research.google.com/github/botkin92/Linear_algebra/blob/lesson_2/lesson_2(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

а) произведения матриц  AB  и  BA  невозможно  
б) размерность матрицы AB - 2 x 3; произведение матриц  BA  невозможно  
в) размерность AB - 8 x 8; размерность BA - 3 x 3  
г) размерность AB - 4 x 4; размерность BA - 4 x 4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [ ]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

In [ ]:
# Новая матрица
C = np.zeros((2, 2))
D = np.zeros((2, 2))

In [ ]:
# Сумма A и B
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      C[i][j] = A[i][j] + B[i][j]
print(C)

[[ 5. -3.]
 [ 3.  5.]]


In [ ]:
# Проверка
A+B

array([[ 5, -3],
       [ 3,  5]])

In [ ]:
# Произведение A на B
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      for k in range(A.shape[1]):
        D[i][j] += A[i][k] * B[k][j]
print(D)

[[  4. -11.]
 [ 12.  -3.]]


In [ ]:
# Проверка
A.dot(B)

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [ ]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1,]])

In [ ]:
D = 3*A - 2*B + 4*C
D

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [ ]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [ ]:
AT = np.array([[A[j][i] for j in range(A.shape[0])] for i in range(A.shape[1])])
AT

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [ ]:
AAT = np.zeros((A.shape[0], AT.shape[1]))
ATA = np.zeros((AT.shape[0], A.shape[1]))
AAT

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Произведение A на AT
for i in range(A.shape[0]):
    for j in range(AT.shape[1]):
      for k in range(A.shape[1]):
        AAT[i][j] += A[i][k] * AT[k][j]
print(AAT)

[[17. 18. 11.]
 [18. 29.  4.]
 [11.  4. 13.]]


In [ ]:
# Проверка
A.dot(AT)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [ ]:
# Произведение AT на A
for i in range(AT.shape[0]):
    for j in range(A.shape[1]):
      for k in range(AT.shape[1]):
        ATA[i][j] += AT[i][k] * A[k][j]
print(ATA)

[[45.  0.]
 [ 0. 14.]]


In [ ]:
# Проверка
AT.dot(A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [ ]:
def matrix_product(mtrx1, mtrx2):
  if range(mtrx1.shape[1])!=mtrx2.shape[0]:
    print "Матрицы не могут быть перемножены"        
  else:
    for i in range(mtrx1.shape[0]):
      for j in range(mtrx2.shape[1]):
        for k in range(mtrx1.shape[1]):
          new_mtrx[i][j] += mtrx1[i][k] * mtrx2[k][j]
    return new_mtrx